version: '3.1'

services:

  mongo:
    build: .
    restart: always
    mem_limit: 2GB
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081

volumes:
  mongodb_data_container: